# Generated by Django 5.1.7 on 2025-05-06 20:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_alter_answer_id_alter_question_id_alter_quiz_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testresult",
            old_name="completed_at",
            new_name="date_taken",
        ),
        migrations.RenameField(
            model_name="testresult",
            old_name="total_questions",
            new_name="total",
        ),
        migrations.AddField(
            model_name="testresult",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
