# Generated by Django 5.1.7 on 2025-05-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_rename_completed_at_testresult_date_taken_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testresult",
            old_name="date_taken",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="testresult",
            name="name",
        ),
        migrations.AlterField(
            model_name="testresult",
            name="score",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="total",
            field=models.PositiveIntegerField(),
        ),
    ]
